### ISSUE TITLE
Potential issue with default values

### ISSUE THREAD

**Issue by gabrielhuang** [ServiceNow/TapeAgents#22]
As you may know, we should never use mutable values such as `[]` or `{}` as python defaults. Or this can lead to hard to catch bugs as soon as the passed objects are modified. Here's an article about it: https://www.pullrequest.com/blog/python-pitfalls-the-perils-of-using-lists-and-dicts-as-default-arguments/

I saw this pattern a few times in the code of agent.py and once in python_interperter,py
<img width="401" alt="image" src="https://github.com/user-attachments/assets/7cca66e3-ebed-46bf-8d82-6f296c54625b">

The correct fix is to use None and do something like `param = param or []`

**Comment by ollmer** [comment]
Solved. Thanks!
